- README.md
- coco.yml
- modules/coco.go
- modules/indexing/document.go
- modules/indexing/init.go
This pull request includes several significant updates across multiple files to enhance the functionality of the Coco application, primarily focusing on document management and API improvements.
* **New API Endpoints for Document Management**:
- Added endpoints for creating, retrieving, updating, deleting, and searching documents in `modules/indexing/document.go`.
- Registered these new API endpoints in `modules/indexing/init.go`.
* **TLS Configuration Change**:
- Disabled TLS by setting `enabled` to `false` in the `coco.yml` configuration file.
* **Indexing API Reference**:
- Included detailed API reference for indexing documents in the `README.md` file.
* **Schema Registration**:
- Updated schema registration in `modules/coco.go` to use `orm.MustRegisterSchemaWithIndexName` for better …
> feat: initialize indexing API implementation

- README.md
- main.go
- modules/assistant/init.go
- modules/assistant/session.go
This pull request includes several changes to add a cancel message feature and integrate the task module into the chat system. The most important changes include updates to the API, modifications to the `sendChatMessage` function, and the addition of the `cancelReplyMessage` function.
* [`modules/assistant/init.go`](diffhunk://#diff-567342d661608019b84961ddd2b5320f56d569a51c1a4c36bc3801cebdfb458cR23-L26): Added a new API method to handle message cancellation.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R197-R208): Added documentation for the cancel message API endpoint.
* [`modules/assistant/session.go`](diffhunk://#diff-763f00436eeeab5043e2cbabb928edcfe95375f538045b0f5626386a2f2f3feaL173-R191): Modified the `sendChatMessage` function …
> feat: add support for canceling in-flight background jobs

- Makefile
- README.md
- coco.yml
- main.go
- modules/coco.go
- modules/common/document.go
- plugins/connectors/google_drive/files.go
- plugins/connectors/google_drive/plugin.go
This pull request includes several changes to add Google Drive integration, update document handling, and modify module registration. The most important changes include the addition of a Google Drive connector, updates to the `Document` struct, and modifications to the `main.go` file to register new modules and plugins.
* Added a new Google Drive connector in `coco.yml` to enable indexing and processing of Google Drive documents.
* Implemented Google Drive file handling in `plugins/connectors/google_drive/files.go`, including functions for token management, file indexing, and file download/export.
* Introduced a new plugin for Google Drive in `plugins/connectors/google_drive/plugin.go` to manage the setup, start, and stop processes.
* Updated the `Document` struct in …
> feat: add google drive connector

- Install.sh
- README.md
> Init script for quickstart

- README.md
- coco.yml
- plugins/connectors/google_drive/api.go
- plugins/connectors/google_drive/files.go
- plugins/connectors/google_drive/plugin.go
This pull request includes several important changes to the Google Drive connector plugin. The changes primarily focus on improving the OAuth flow, handling credentials, and enhancing the indexing process for Google Drive files.
* Added new endpoints for initiating and handling the OAuth flow in `plugins/connectors/google_drive/api.go`.
* Updated `coco.yml` to use a single credential file and set a polling interval.
* Refactored the `startIndexingFiles` function to handle pagination, track the most recent modified time, and improve error handling in `plugins/connectors/google_drive/files.go` [[1]](diffhunk://#diff-998d146d9dbe5ae2861beb0339ffbf04fcef3f67252b1248d2a5d5e5c8af7a0dL5-R113) [[2]](diffhunk://#diff-998d146d9dbe5ae2861beb0339ffbf04fcef3f67252b1248d2a5d5e5c8af7a0dL169-R162) …
> feat: Improve incremental indexing of Google Drive files and enhance OAuth flow

- Install.sh
- README.md
- coco.yml
- Updated `coco.yml` to load the Easysearch password from keystore
- Readme files accordingly
> chore: updated coco server to load easysearch password from keystore

- .github/PULL_REQUEST_TEMPLATE.md
This pull request introduces a new pull request template to ensure consistency and thoroughness in code reviews. The template includes sections for describing the PR, the rationale behind the changes, and a checklist to verify standards compliance.
Changes to pull request template:
* [`.github/PULL_REQUEST_TEMPLATE.md`](diffhunk://#diff-18813c86948efc57e661623d7ba48ff94325c9b5421ec9177f724922dd553a35R1-R11): Added sections for PR description, rationale, and a checklist to ensure the PR title is descriptive, commit messages follow semantic conventions, necessary tests are added, performance tests are checked, and necessary documents are included for new features.
> chore: update github PR template

- modules/search/search.go
- modules/search/suggest.go
- [] Necessary tests are added
> chore: update default page size to 10

- modules/search/search.go
> feat: ignore empty query

- modules/assistant/session.go
> feat: add field message_id to push messages

- plugins/connectors/google_drive/api.go
- plugins/connectors/google_drive/plugin.go
> feat: add reset api to google_drive's connector

- Install.sh
- README.md
Replaced the OCR server with LLM model
LLM is a better way for OCR nowadays.
> replaced the OCR server with LLM model

- LICENSE
- Makefile
> chore: update license

- modules/common/document.go
- modules/search/search.go
- plugins/connectors/google_drive/plugin.go
> chore: misc changes

- main.go
> chore: update terminal header

- plugins/connectors/google_drive/plugin.go
> chore: update missing import

- docs/content.en/docs/references/connectors/hugo_site.md
- plugins/connectors/google_drive/files.go
- plugins/connectors/google_drive/plugin.go
- plugins/connectors/yuque/collect.go
- plugins/connectors/yuque/plugin.go
> chore: fix icon link

- docs/content.en/docs/references/connectors/google_drive.md
- docs/content.en/docs/references/connectors/hugo_site.md
- docs/content.en/docs/references/connectors/yuque.md
> chore: update api docs

- docs/content.en/docs/release-notes/_index.md
- modules/assistant/session.go
- modules/common/document.go
> feat: init support for RAG

- docs/content.en/docs/getting-started/install.md
- docs/content.en/docs/references/_index.md
- docs/content.en/docs/references/account/_index.md
- docs/content.en/docs/references/account/access_token.md
- docs/content.en/docs/references/account/authentication.md
- docs/content.en/docs/references/account/password.md
- docs/content.en/docs/references/account/profile.md
- docs/content.en/docs/references/assistant.md
- docs/content.en/docs/references/install.md
- docs/content.en/docs/references/settings.md
> chore: update docs

- web/src/components/stateless/common/GlobalLoading.tsx
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/guide/modules/LLMForm.tsx
- web/src/pages/guide/modules/UserForm.tsx
- web/src/pages/login/modules/LoginForm.tsx
- web/src/types/api.d.ts
- web/src/types/app.d.ts
> fix: adjust locales

- web/package.json
- web/src/constants/reg.ts
- web/src/hooks/common/form.ts
- web/src/pages/settings/modules/LLM.tsx
- web/src/service/api/server.ts
- web/src/service/request/index.ts
> chore: update settings

- web/src/constants/app.ts
- web/src/layouts/modules/global-header/components/UserAvatar.tsx
- web/src/locales/langs/en-us/common.ts
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/common.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/ai-assistant/index.tsx
- web/src/pages/home/index.tsx
- web/src/pages/login/index.tsx
- web/src/pages/login/modules/CocoAI.tsx
- web/src/pages/login/modules/LoginForm.tsx
- web/src/router/guard/index.ts
- web/src/theme/settings.ts
- web/src/types/app.d.ts
> chore: add Launch CocoAI

- web/src/router/guard/index.ts
- web/src/types/api.d.ts
> chore: add initialization verification

- web/src/pages/guide/modules/LLMForm.tsx
- web/src/pages/settings/modules/LLM.tsx
> chore: adjust llm's form

- web/src/pages/home/index.tsx
> fix: lose server's settings after editing

- web/src/pages/guide/modules/LLMForm.tsx
- web/src/pages/settings/modules/LLM.tsx
> fix: lose llm's settings

- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/guide/modules/LLMForm.tsx
- web/src/pages/settings/modules/LLM.tsx
- web/src/types/app.d.ts
> chore: add keepalive, token to llm's form

- web/src/components/button-radio/index.tsx
- web/src/pages/data-source/list/index.tsx
- web/src/pages/settings/modules/LLM.tsx
- web/src/types/auto-imports.d.ts
> chore: add icon to datesource list

- web/src/constants/reg.ts
- web/src/hooks/common/form.ts
> fix: adjust endpoint validation

- web/src/pages/guide/modules/Guide.tsx
- web/src/pages/login/index.tsx
> fix: adjust styles of guide

- docs/content.en/docs/references/account/authentication.md
> chore: remove basic auth doc

- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/en-us/route.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/locales/langs/zh-cn/route.ts
- web/src/pages/data-source/edit/[id].tsx
- web/src/pages/data-source/list/index.tsx
- web/src/pages/data-source/new/index.tsx
> chore: update locales of data source

- coco.yml
- web/src/components/datasource/indexing_scope/index.jsx
> update default settings

- web/ErrorBoundary.tsx
- web/build/plugins/info.ts
- web/src/plugins/loading.ts
- web/src/theme/settings.ts
> fix: override theme settings

- plugins/connectors/google_drive/plugin.go
> fix: avoid panic when Google Drive credential config is missing

- web/src/components/stateless/common/GlobalLoading.tsx
- web/src/pages/guide/modules/LLMForm.tsx
- web/src/plugins/loading.ts
> chore: adjust styles of loading

- coco.yml
- core/config.go
- modules/common/config.go
- modules/system/settings.go
- plugins/connectors/google_drive/api.go
- plugins/connectors/google_drive/plugin.go
- plugins/connectors/helper.go
- plugins/connectors/hugo_site/plugin.go
- plugins/connectors/notion/plugin.go
- plugins/connectors/yuque/plugin.go
- web/src/components/datasource/data_sync/index.jsx
- web/src/components/datasource/type/index.jsx
- web/src/pages/data-source/edit/[id].tsx
- web/src/pages/settings/index.tsx
- web/src/pages/settings/modules/Connector.tsx
> feat: add google drive connector settings

- modules/assistant/background_job.go
> chore: echo message before pick docs

- modules/assistant/background_job.go
- modules/coco.go
- modules/common/config.go
> chore: expose models to config

- web/src/pages/data-source/list/index.tsx
> feat: support toggling synchronization in datasource list

- coco.yml
- modules/assistant/background_job.go
- modules/assistant/rag/llm_generate.go
- modules/coco.go
- modules/common/config.go
> chore: update to support ollama

- coco.yml
> chore: default banner

- docs/content.en/docs/getting-started/install.md
This pull request includes a significant update to the `docs/content.en/docs/getting-started/install.md` file. The changes introduce a detailed script for deploying and managing the Coco Server using Docker.
Key changes include:
* Added a comprehensive bash script for quick deployment of the Coco Server using Docker, including commands and explanations for starting, stopping, and removing the server container and image.
* Provided a customizable Docker run command with detailed parameter explanations for more advanced users who need to adjust the server configuration based on specific requirements.
> docs: update docker install guide

- docs/content.en/docs/getting-started/install.md
This pull request includes updates to the `docs/content.en/docs/getting-started/install.md` file to translate and clarify the Docker deployment script and related command explanations from Chinese to English.
Documentation improvements:
* Translated the comments and command explanations from Chinese to English for better accessibility and understanding.
* Improved clarity and consistency in the Docker command explanations, including details on command options and parameters.
> docs: typo update docker install guide

- modules/assistant/background_job.go
- modules/coco.go
> fix: empty response

- web/.env
- web/src/service/request/error.ts
- web/src/types/app.d.ts
> fix: redirect to the login page when the token expires

- docs/content.en/docs/release-notes/_index.md
- plugins/connectors/helper.go
> fix: fatal error for concurrent map writes

- docs/content.en/docs/release-notes/_index.md
- modules/assistant/background_job.go
- plugins/security/account.go
> feat: catch error in background message processing task

- docs/content.en/docs/release-notes/_index.md
- modules/assistant/background_job.go
- modules/assistant/rag/query_analysis.go
- modules/assistant/rag/query_analysis_test.go
- plugins/connectors/google_drive/plugin.go
- plugins/connectors/helper.go
> chore: optimize rag tasks

- web/src/pages/data-source/edit/[id].tsx
refine datasource update UI for better usability
> improvement: refine datasource update UI for better usability

- docs/content.en/docs/getting-started/setup.md
- docs/content.en/docs/release-notes/_index.md
- modules/coco.go
- modules/indexing/document.go
> chore: throw error on invalid user during WebSocket connection

- docs/content.en/docs/references/attachment.md
- modules/assistant/attachment.go
- modules/assistant/init.go
> feat: add attachment search api

- docs/content.en/docs/references/assistant.md
- docs/content.en/docs/release-notes/_index.md
- modules/assistant/websocket.go
- modules/coco.go
> feat: allow user pass websocket session id via request header

- plugins/security/access_token.go
> chore: remove token limit temporarily

- core/context.go
- docs/content.en/docs/references/attachment.md
- docs/content.en/docs/release-notes/_index.md
- modules/assistant/attachment.go
- modules/assistant/init.go
- modules/common/attachment.go
- modules/common/document.go
- plugins/connectors/google_drive/files.go
> feat: support delete attachment

- web/src/pages/api-token/list/index.tsx
temporarily remove API token count check
> fix: temporarily remove API token count check

- web/src/pages/data-source/list/index.tsx
- web/src/pages/integration/list/index.tsx
- web/src/service/api/integration.ts
> chore: add the default sorter to the integration list

- config/widget/wrapper.js
- docs/content.en/docs/release-notes/_index.md
- modules/integration/init.go
- modules/integration/wrapper.go
- plugins/security/filter/cors.go
> feat: add widget wrapper

- modules/assistant/background_job.go
- modules/assistant/websocket.go
- modules/coco.go
> refactor: refactoring for websocket

- docs/content.en/docs/references/integration.md
- docs/content.en/docs/release-notes/_index.md
- modules/integration/init.go
- modules/integration/suggest.go
> feat: add suggested chat topics for widget

- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/connector/new/index.tsx
- web/src/pages/data-source/edit/[id].tsx
- web/src/pages/data-source/new-first/index.tsx
add default icon and URL for document insert script
> chore: add default icon and URL for document insert script

- config/widget/wrapper.js
- modules/integration/init.go
- modules/integration/wrapper.go
> refactor: refactoring widget script wrapper

- modules/common/integration.go
add fields type_options and hotkey for integration
> feat: add fields options and hotkey for integration

- docs/content.en/docs/release-notes/_index.md
- modules/connector/init.go
- modules/datasource/init.go
- plugins/security/filter/json_mask.go
> feat: add support to filter senstive fields

- core/context.go
- core/validate.go
- modules/common/integration.go
- modules/datasource/datasource.go
- modules/integration/integration.go
- modules/search/search.go
support filtering datasources with integration
> feat: support filtering datasources with integration

- modules/assistant/init.go
- modules/attachment/init.go
- modules/connector/init.go
- modules/datasource/init.go
- modules/document/init.go
- modules/integration/init.go
- modules/search/init.go
- modules/system/init.go
> fix: incorrect import

- web/widgets/searchbox/src/DocSearch.jsx
- web/widgets/searchbox/src/styles/modal.css
> chore: adjust searchbox‘s styles

- docs/content.en/docs/references/assistant.md
- docs/content.en/docs/release-notes/_index.md
- modules/assistant/init.go
- modules/assistant/session.go
- modules/common/session.go
> feat: add chat session management api

- docs/content.en/docs/release-notes/_index.md
- plugins/connectors/yuque/collect.go
> fix: personal token was not well supported for Yuque connector

- plugins/connectors/yuque/collect.go
> fix: incorrect yuque url

- config/widget/wrapper.js
- web/widgets/searchbox/index.html
- web/widgets/searchbox/src/DocSearch.jsx
- web/widgets/searchbox/src/DocSearchFloatButton.jsx
- web/widgets/searchbox/src/DocSearchModal.jsx
> fix: adjust searchbox modal's position

- web/widgets/searchbox/package.json
- web/widgets/searchbox/src/DocSearch.jsx
> fix: resolve dependencies of searchbox

- docs/content.en/docs/release-notes/_index.md
- web/src/pages/integration/modules/EditForm.tsx
> chore: add placeholder to icon in integration form

- web/src/router/elegant/routes.ts
- web/src/router/guard/index.ts
> fix: redirect to the home page when accessing the login page if logged in

- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
- web/widgets/searchbox/src/DocSearchModal.jsx
- web/widgets/searchbox/src/styles/button.css
- web/widgets/searchbox/src/styles/modal.css
> chore: enhance UI for searchbox

- web/src/components/stateful/ThemeSchemaSwitch.tsx
- web/src/locales/langs/zh-cn/theme.ts
- web/src/router/elegant/routes.ts
- web/src/store/slice/theme/index.ts
> chore: cache theme settings when switching the theme

- web/widgets/searchbox/src/styles/button.css
> fix: enhance styles of searchbox

- web/widgets/searchbox/src/styles/button.css
> chore: enhance UI for searchbox's buttons

- web/src/locales/langs/en-us/page.ts
- web/src/pages/integration/modules/InsertCode.tsx
> chore: update integration's script

- docs/content.en/docs/release-notes/_index.md
- web/widgets/searchbox/src/DocSearch.jsx
- web/widgets/searchbox/src/DocSearchFloatButton.jsx
- web/widgets/searchbox/src/DocSearchModal.jsx
> chore: follow system theme if searchbox's theme is set to `auto`

- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/integration/modules/EditForm.tsx
> chore: add Enabled to integration form

- docs/content.en/docs/release-notes/_index.md
- web/pnpm-lock.yaml
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/integration/list/index.tsx
- web/src/service/api/integration.ts
- web/widgets/searchbox/package.json
- web/widgets/searchbox/src/DocSearchButton.jsx
- web/widgets/searchbox/src/styles/button.css
> chore: add suggested topics to integration

- web/src/pages/login/modules/CocoAI.tsx
> fix: stop the timer after click `Launch Coco AI`

- docs/content.en/docs/release-notes/_index.md
- modules/integration/wrapper.go
> chore: skip handle wrapper for disabled widget

- config/setup/en-US/assistant.tpl
- modules/assistant/background_job.go
- modules/assistant/session.go
> chore: update rag prompts

- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
> chore: update searchbox's dependencies

- web/src/components/common/IconWrapper.tsx
> chore: adjust icon's styles in dark mode

- web/src/common/src/DropdownList/index.module.less
> chore: adjust dropdownlist's styles

- coco.yml
> chore: update default config

- docs/content.en/docs/references/assistant.md
- modules/assistant/assistant.go
- modules/assistant/init.go
- web/src/locales/langs/en-us/common.ts
- web/src/locales/langs/zh-cn/common.ts
- web/src/pages/ai-assistant/list/index.tsx
- web/src/service/api/assistant.ts
add support for cloning assistants
> feat: add support for cloning assistants

- modules/common/config.go
> fix: default login url

- modules/assistant/background_job.go
> chore: ignore empty chunk message

- config/setup/en-US/connector.tpl
- config/setup/zh-CN/connector.tpl
- modules/system/initialize.go
- web/src/pages/connector/edit/[id].tsx
add default config for builtin connector google drive
> chore: add default config for google drive

- NOTICE
- go.mod
- modules/assistant/background_job.go
- modules/assistant/langchain/adapter.go
- modules/assistant/langchain/adapter_test.go
- modules/common/mcp_server.go
> feat: add mcp serversupport for stdin type

- docs/content.en/docs/release-notes/_index.md
- web/src/pages/ai-assistant/modules/EditForm.tsx
- web/src/pages/connector/new/icon_selector.jsx
- web/src/pages/model-provider/edit/[id].tsx
- web/src/pages/model-provider/new/index.tsx
support user-provided icon URL in icon component
> feat: support user-provided icon URL in icon component

- config/widget/wrapper.js
- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
- web/widgets/searchbox/src/DocSearch.jsx
> chore: render the UI after the stylesheet is loaded in Searchbox

- config/widget/wrapper.js
- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
> chore: fix invalid MIME type for wrapper js

- web/src/pages/integration/modules/InsertCode.tsx
- web/widgets/searchbox/src/DocSearch.jsx
- web/widgets/searchbox/src/DocSearchModal.jsx
> chore: optimize searchbox's rendering

- coco.yml
- docs/content.en/docs/release-notes/_index.md
- modules/search/search.go
> chore: update default query template

- config/setup/en-US/datasource.tpl
- config/setup/zh-CN/datasource.tpl
> chore: update default datasources

- config/setup/en-US/mcp_server.tpl
- config/setup/zh-CN/mcp_server.tpl
- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
> chore: update setup data, update searchbox to v1.1.13

- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/ai-assistant/modules/ModelSelect.tsx
- web/src/pages/ai-assistant/modules/ModelSettings.tsx
- web/widgets/searchbox/src/DocSearchButton.jsx
> chore: add prompt settings to Model

- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/ai-assistant/modules/ModelSettings.tsx
- web/src/pages/model-provider/edit/[id].tsx
- web/src/pages/model-provider/new/index.tsx
> chore: add reasoning to Model Settings

- modules/assistant/background_job.go
fix datasource filtering config not working in assistant settings
> fix: datasource filtering config not working in assistant settings

- modules/assistant/assistant.go
- modules/assistant/background_job.go
- modules/assistant/rag/llm_generate.go
- modules/assistant/rag/query_analysis.go
- modules/common/assistant.go
- modules/common/prompts.go
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/ai-assistant/modules/DatasourceConfig.tsx
- web/src/pages/ai-assistant/modules/DeepThink.tsx
- web/src/pages/ai-assistant/modules/EditForm.tsx
- web/src/pages/ai-assistant/modules/ModelSettings.tsx
> feat: add additional deepthink params for assistant

- docs/content.en/docs/release-notes/_index.md
- modules/common/config.go
> fix: update default login url

- modules/assistant/background_job.go
- modules/assistant/rag/query_analysis.go
- modules/assistant/rag/template.go
> refactor: refactoring prompt template util

- modules/assistant/background_job.go
- modules/common/assistant.go
> fix: merged id should not affect the original field

- docs/content.en/docs/release-notes/_index.md
This PR create by  to updates the release notes.
> chore: update release notes for publish 0.4.0-2018

- config/setup/en-US/model_provider.tpl
- config/setup/zh-CN/model_provider.tpl
- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
> chore: misc update

- modules/assistant/background_job.go
> chore: check feature switch before process

- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
> chore: update search-chat version

- web/pnpm-lock.yaml
> build: build serach box version

- modules/system/initialize.go
> chore: refactoring fasttemplate

- docs/content.en/docs/release-notes/_index.md
- modules/assistant/session.go
> chore: sort chat history by created

- docs/content.en/docs/release-notes/_index.md
- modules/common/assistant.go
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/ai-assistant/edit/[id].tsx
- web/src/pages/ai-assistant/modules/DatasourceConfig.tsx
- web/src/pages/ai-assistant/modules/EditForm.tsx
- web/src/pages/ai-assistant/modules/MCPConfig.tsx
> chore: add enabled by default params

- docs/content.en/docs/release-notes/_index.md
- web/src/constants/reg.ts
- web/src/locales/langs/en-us/form.ts
- web/src/locales/langs/zh-cn/form.ts
> chore: password support more special characters

- coco.yml
- docs/content.en/docs/release-notes/_index.md
- modules/common/assistant.go
- modules/common/config.go
- modules/common/server_config.go
- modules/search/search.go
- modules/system/initialize.go
> feat: allow to convert icon to base64

- web/src/layouts/modules/global-header/components/PasswordModal.tsx
- web/src/pages/login/modules/LoginForm.tsx
> chore: adjust password verification in login and password modification

- docs/content.en/docs/release-notes/_index.md
- modules/common/config.go
- modules/common/datasource.go
- modules/common/icon.go
- modules/connector/connector.go
- modules/datasource/datasource.go
- modules/search/search.go
> fix: incorrect datasource icon

- docs/content.en/docs/release-notes/_index.md
- web/src/pages/ai-assistant/modules/EditForm.tsx
- web/src/pages/model-provider/new/index.tsx
- web/src/utils/common.ts
fix: resolve compatibility issue with crypto.randomUUID when creating model provider
> fix: resolve compatibility issue with crypto.randomUUID

- web/src/pages/ai-assistant/modules/DatasourceConfig.tsx
- web/src/pages/ai-assistant/modules/MCPConfig.tsx
> chore: delete button linkage

- docs/content.en/docs/release-notes/_index.md
> docs: update notes

- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
> build: upgrade search-chat version

- web/src/pages/ai-assistant/modules/EditForm.tsx
> chore: adjust form of simple mode in AI Assistant

- web/src/pages/ai-assistant/modules/EditForm.tsx
> chore: adjust advanced form of simple mode in AI Assistant

- modules/search/search.go
> chore: optimize assistant search

- modules/assistant/init.go
> chore: fix permission settings

- modules/system/init.go
> chore: remove unncessary permission

- docs/content.en/docs/release-notes/_index.md
- modules/common/assistant.go
- modules/common/datasource.go
- modules/common/mcp_server.go
> chore: add placeholder to chat settings

- docs/content.en/docs/release-notes/_index.md
- web/src/components/common/tags.tsx
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/ai-assistant/modules/EditForm.tsx
- web/src/service/api/assistant.ts
> chore: add placeholder, category and tags to AI Assistant

- web/src/pages/ai-assistant/modules/EditForm.tsx
- web/src/pages/ai-assistant/new/index.tsx
- web/src/pages/connector/new/index.tsx
> fix: failed to save the form in AI Assistant

- modules/integration/integration.go
> chore: use save method to handle integrated update operation

- modules/llm/init.go
> fix: mcp server list not show up

- modules/llm/init.go
- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
> chore: upgrade searchbox

- config/setup/en-US/assistant.tpl
- config/setup/en-US/model_provider.tpl
- config/setup/zh-CN/assistant.tpl
- config/setup/zh-CN/model_provider.tpl
- modules/assistant/streaming-http.go
- modules/system/initialize.go
> chore: update init template

- docs/content.en/docs/release-notes/_index.md
- plugins/security/filter/fingerprint_throttle.go
> feat: add throttle filter wth request fingerprint #294

- plugins/security/filter/fingerprint_throttle.go
> chore: less verbose logging message

- docs/content.en/docs/release-notes/_index.md
This PR create by github actions to updates the release notes.
> chore: update release notes for publish 0.5.1-2252

- core/config.go
- docs/content.en/docs/release-notes/_index.md
- modules/system/initialize.go
- plugins/security/account.go
> feat: multi-user login support

- web/src/pages/ai-assistant/modules/AIAssistantSelect.tsx
> fix: lose filters when click refresh in AI Assistant selector

- web/pnpm-lock.yaml
> chore: update pnpm-lock.yaml

- web/src/pages/settings/index.tsx
> chore: fix duplicate requests in settings

- modules/assistant/assistant.go
> chore: use save to update assistant

- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
- web/widgets/searchbox/src/DocSearch.jsx
- web/widgets/searchbox/src/DocSearchModal.jsx
> chore: adjust unmounting of searchbox's modal

- docs/content.en/docs/release-notes/_index.md
- modules/assistant/background_job.go
> fix: unchecked datasource/mcp_server not working

- core/search.go
- modules/assistant/session.go
- modules/connector/connector.go
- modules/datasource/datasource.go
- modules/llm/mcp_server.go
> refactor: refactoring search

- web/src/components/License/LicenseTrigger.jsx
> chore: adjust locales of `About` in menu

- modules/assistant/assistant.go
- modules/connector/connector.go
- modules/datasource/datasource.go
- modules/llm/mcp_server.go
> fix: fix search api backward compatibility

- core/validate.go
- modules/assistant/assistant.go
- modules/assistant/background_job.go
- modules/assistant/rag/query_analysis.go
- modules/assistant/session.go
- modules/attachment/attachment.go
- modules/datasource/datasource.go
- modules/integration/integration.go
- modules/integration/suggest.go
- modules/integration/wrapper.go
- modules/search/recommend.go
- modules/search/search.go
- modules/search/suggest.go
- modules/system/settings.go
- plugins/connectors/google_drive/api.go
- plugins/connectors/google_drive/files.go
- plugins/connectors/notion/plugin.go
- plugins/connectors/yuque/plugin.go
- plugins/security/filter/permission.go
> refactor: refactoring error handling

- web/src/components/stateless/common/ListContainer.tsx
- web/src/pages/ai-assistant/list/index.tsx
- web/src/pages/api-token/list/index.tsx
- web/src/pages/data-source/list/index.tsx
- web/src/pages/integration/list/index.tsx
- web/src/pages/mcp-server/list/index.tsx
- web/src/pages/model-provider/list/index.tsx
- web/src/pages/settings/index.scss
- web/src/pages/settings/modules/AppSettings.tsx
- web/src/pages/settings/modules/Connector.tsx
- web/src/types/auto-imports.d.ts
> chore: adjust list container

- docs/content.en/docs/release-notes/_index.md
This PR create by github actions to updates the release notes.
> chore: update release notes for publish 0.6.0

- web/widgets/searchbox/src/DocSearch.jsx
> fix: repeated rendering of searchbox

- core/validate.go
- docs/content.en/docs/release-notes/_index.md
- modules/integration/integration.go
- plugins/security/access_token.go
- plugins/security/account.go
- plugins/security/filter/permission.go
> refactor: refactoring user id

- docs/content.en/docs/references/assistant.md
- docs/content.en/docs/release-notes/_index.md
- modules/assistant/init.go
- modules/assistant/session.go
> feat: add http_streaming based chat api

- docs/content.en/docs/release-notes/_index.md
- modules/assistant/background_job.go
> chore: skip empty response chunks

- docs/content.en/docs/release-notes/_index.md
- web/src/pages/ai-assistant/modules/AIAssistantSelect.tsx
- web/src/pages/data-source/modules/DataSourceSelect.tsx
- web/src/service/api/assistant.ts
- web/src/service/api/data-source.ts
- web/src/service/request/es.ts
> fix: query parameter "filter" is not working

- docs/content.en/docs/release-notes/_index.md
- modules/datasource/init.go
- modules/integration/init.go
- modules/llm/init.go
- modules/system/init.go
- plugins/security/filter/json_mask.go
> chore: mask more senstive search results

- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
> build: update search chat version

- docs/content.en/docs/release-notes/_index.md
- modules/attachment/attachment.go
- modules/attachment/init.go
> refactor: refactoring attachement api

- docs/content.en/docs/release-notes/_index.md
- modules/common/assistant.go
> feat: add file upload config

- docs/content.en/docs/release-notes/_index.md
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/ai-assistant/modules/EditForm.tsx
- web/src/pages/ai-assistant/modules/UploadConfig.tsx
- web/src/pages/ai-assistant/new/index.tsx
> chore: add upload settings to assistant

- README.md
> docs: add deep wiki docs

- core/validate.go
- docs/content.en/docs/release-notes/_index.md
- modules/assistant/assistant.go
- modules/assistant/session.go
- modules/assistant/websocket.go
- modules/attachment/attachment.go
- modules/common/assistant.go
- modules/common/datasource.go
- modules/common/mcp_server.go
- modules/connector/connector.go
- modules/datasource/datasource.go
- modules/document/document.go
- modules/integration/integration.go
- modules/integration/wrapper.go
- modules/llm/init.go
- modules/llm/mcp_server.go
- modules/llm/model_provider.go
- modules/search/init.go
- modules/search/search.go
- plugins/security/access_token.go
- plugins/security/account.go
- plugins/security/filter/auth.go
- plugins/security/filter/permission.go
- web/src/pages/home/index.tsx
> refactor: refactoring ORM and security interface

- coco.yml
- modules/common/config.go
- modules/common/server_config.go
> refactor: refactoring managed config

- docs/content.en/docs/release-notes/_index.md
- modules/attachment/attachment.go
- modules/common/attachment.go
> chore: remove session_id check in attachment upload api

- docs/content.en/docs/release-notes/_index.md
- web/pnpm-lock.yaml
- web/src/pages/integration/modules/EditForm.tsx
- web/widgets/searchbox/index.html
- web/widgets/searchbox/package.json
- web/widgets/searchbox/src/DocSearch.jsx
- web/widgets/searchbox/src/DocSearchModal.jsx
> chore: add formatUrl to searchbox

- web/src/icons/index.js
> fix: add local icons

- modules/search/search.go
> fix: reverse data source filter in v2

- docs/content.en/docs/release-notes/_index.md
- modules/assistant/session.go
- modules/common/message.go
> fix: chat api with attachments

- docs/content.en/docs/release-notes/_index.md
- go.mod
- go.sum
- modules/assistant/background_job.go
- modules/llm/mcp_server.go
> fix: prevent nil exception during LLM intent parsing on error

- Makefile
- config/setup/en-US/assistant.tpl
- modules/common/prompts.go
> chore: update default prompt

- plugins/connectors/google_drive/plugin.go
- plugins/connectors/hugo_site/plugin.go
- plugins/connectors/notion/plugin.go
- plugins/connectors/rss/plugin.go
- plugins/connectors/yuque/plugin.go
> chore: fix typo in panic error messages

- config/setup/en-US/assistant.tpl
- config/setup/zh-CN/assistant.tpl
- docs/content.en/docs/release-notes/_index.md
- modules/system/initialize.go
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/guide/modules/Guide.tsx
- web/src/pages/guide/modules/LLMForm.tsx
support default model reasoning config on initialization
> feat: support default model reasoning config on initialization

- web/src/layouts/modules/global-breadcrumb/index.tsx
Make the navigation path clickable.
Usability enhancement
> chore: make navigation path clickable

- web/src/pages/ai-assistant/modules/UploadConfig.tsx
- web/src/pages/ai-assistant/new/index.tsx
> fix: cannot update upload config in assistant form

- docs/content.en/docs/release-notes/_index.md
- web/src/pages/ai-assistant/modules/ModelSelect.tsx
properly handle default value for prompt template
> chore: properly handle default value for prompt template

- docs/content.en/docs/release-notes/_index.md
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/integration/edit/[id].tsx
- web/src/pages/integration/modules/InsertCode.tsx
> chore: set button preview to disabled if integration is disabled

- docs/content.en/docs/references/search.md
- modules/assistant/assistant.go
- modules/document/document.go
- modules/integration/integration.go
- modules/llm/model_provider.go
> refactor: refactoring search api

- web/src/common/src/DropdownList/List.module.less
- web/src/pages/data-source/edit/[id].tsx
- web/src/service/api/model-provider.ts
> fix: lose data in model select

- web/src/components/License/LicenseTrigger.jsx
- web/src/pages/ai-assistant/modules/AIAssistantSelect.tsx
- web/src/pages/ai-assistant/modules/DatasourceConfig.tsx
- web/src/pages/ai-assistant/modules/EditForm.tsx
- web/src/pages/data-source/modules/DataSourceSelect.tsx
- web/src/pages/integration/modules/EditForm.tsx
- web/src/pages/integration/modules/SearchBoxForm.tsx
- web/src/pages/login/modules/CocoAI.tsx
- web/src/pages/settings/modules/AppSettings.tsx
- web/src/pages/settings/modules/ChartStartPage.tsx
> chore: adjust result of useRequest

- web/.npmignore
- web/pnpm-lock.yaml
- web/pnpm-workspace.yaml
> fix: build web failed

- web/src/pages/integration/modules/InsertCode.tsx
> fix: duplicate copying script in integration

- web/pnpm-lock.yaml
- web/widgets/searchbox/package.json
> build: update search-chat version

- docs/content.en/docs/getting-started/install.md
- plugins/security/account.go
> docs: fix install use random password

- modules/assistant/background_job.go
- modules/common/datasource.go
- modules/common/prompts.go
> chore: add description to datasource

- docs/content.en/docs/getting-started/install.md
> docs: fix install security admin password describe and docker volumes 

- modules/assistant/session.go
- modules/connector/connector.go
> chore: add wait_for_refresh to delete api

- docs/content.en/docs/release-notes/_index.md
- plugins/connectors/notion/plugin.go
- plugins/connectors/notion/types.go
Extract Content For Notion Connector #70
> feat: Extract Content For Notion Connector #70

- coco.yml
- core/validate.go
- docs/content.en/docs/references/account/access_token.md
- go.mod
- go.sum
- modules/assistant/assistant.go
- modules/connector/connector.go
- modules/datasource/datasource.go
- modules/document/document.go
- modules/integration/integration.go
- modules/integration/wrapper.go
- plugins/connectors/confluence/plugin.go
- plugins/connectors/google_drive/files.go
- plugins/connectors/hugo_site/plugin.go
- plugins/connectors/local_fs/plugin.go
- plugins/connectors/network_drive/plugin.go
- plugins/connectors/notion/plugin.go
- plugins/connectors/rss/plugin.go
- plugins/connectors/s3/plugin.go
- plugins/connectors/yuque/collect.go
- plugins/security/access_token.go
- plugins/security/account.go
- plugins/security/filter/auth.go
- plugins/security/filter/permission.go
- plugins/security/init.go
- web/src/pages/api-token/list/index.tsx
- web/src/service/api/api-token.ts
> refactor: refactoring security infra

- web/src/hooks/common/queryParams.ts
- web/src/pages/data-source/detail/[id].tsx
> chore: adjust filter of query params

- web/src/pages/data-source/detail/[id].tsx
- web/src/service/request/es.ts
> chore: support access docs via path hierarchy manner in datasource

- coco.yml
- plugins/processors/summary/processor.go
- plugins/summary/processor.go
> refactor: refactoring summary processor

- docs/content.en/docs/references/connectors/google_drive.md
> chore: add missing docs for google drive

- web/src/pages/settings/modules/Connector.tsx
- web/src/service/api/connector.ts
> fix: incorrect params of Connector

- web/README.md
> chore: update web readme

- modules/datasource/datasource.go
- modules/search/search.go
Depends on PR https://github.com/infinilabs/framework/pull/216
> refactor: refactoring search apis

- docs/content.en/docs/release-notes/_index.md
- web/src/pages/api-token/list/index.tsx
- web/src/pages/integration/list/index.tsx
> chore: add icon to list items

- config/setup/en-US/datasource.tpl
- config/setup/zh-CN/datasource.tpl
- docs/content.en/docs/references/connectors/feishu.md
- docs/content.en/docs/release-notes/_index.md
- modules/common/datasource.go
- modules/datasource/datasource.go
- plugins/connectors/base.go
- plugins/connectors/feishu/README.md
- plugins/connectors/feishu/api.go
- plugins/connectors/feishu/feishu_plugin.go
- plugins/connectors/feishu/lark_plugin.go
- plugins/connectors/google_drive/api.go
- plugins/connectors/google_drive/plugin.go
- plugins/connectors/hugo_site/plugin.go
- plugins/connectors/notion/plugin.go
- plugins/connectors/yuque/plugin.go
- web/src/components/datasource/data_sync/index.jsx
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/data-source/edit/[id].tsx
- web/src/pages/data-source/list/index.tsx
- web/src/pages/data-source/new/index.tsx
- web/src/types/api.d.ts
This pull request refactors how datasource synchronization settings are represented and managed throughout the codebase. The main change is replacing the flat `sync_enabled` and related fields with a structured `sync` object, which groups synchronization configuration (enabled, interval, and strategy) together. This update affects backend models, API logic, plugin connectors, documentation, and frontend components to ensure consistency and improved maintainability.
**Backend Model and API Updates:**
* Replaced the `sync_enabled` boolean with a `SyncConfig` struct (`sync`) in the `DataSource` model, encapsulating `enabled`, `interval`, and `strategy` fields. Updated all relevant code to use this new structure, including plugin queries and OAuth flows. …
> refactor: refactoring datasource sync management

- config/setup/en-US/connector.tpl
- modules/common/hierarchy_path.go
- plugins/connectors/gitlab/converter.go
- plugins/connectors/google_drive/files.go
- plugins/connectors/google_drive/plugin.go
> refactor: refactoring google drive connector

- docs/content.en/docs/release-notes/_index.md
- plugins/connectors/s3/plugin.go
> fix: fix S3 connector icon issue

- docs/content.en/docs/release-notes/_index.md
> docs: release notes for 0.8.0
