infinilabs/coco-server

- coco.yml
- modules/common/document.go
- modules/search/init.go
This pull request includes significant updates to the Elasticsearch configuration and the document structure in the codebase, as well as a minor addition to the API handler initialization.
* [`coco.yml`](diffhunk://#diff-461bb31f066abaf4260e1409e70068530cccf332d5b44ce8174eb39cbc253e23R22-R47): Added an index prefix, template override, and a detailed template configuration for the `coco-search` index, including settings for analysis and mappings.
* [`modules/common/document.go`](diffhunk://#diff-85818a05e195a012b8aec7cf396c94651e47a53f2fa13a05c3ee47841da25db3L14-R42): Added `elastic_mapping` tags to the `Document` struct fields for better Elasticsearch integration, including mapping types and indexing options. Introduced a new `SearchText` field for enhanced search capabilities.
* …
> feat: add default index template and schema to document

- docs/content.en/docs/references/api/assistant.md
- docs/content.en/docs/release-notes/_index.md
- modules/assistant/session.go
It seems will have issue to  forward headers with underscore, use hyphen instead.
> fix: update header key to avoid using underscores

- .gitignore
Added the DevOps code scanner ignore folder for this project
Enforced DevOps process of code quality control
> added sonar scanner ignore folder

- coco.yml
- docs/content.en/docs/references/document.md
- modules/coco.go
- modules/common/datasource.go
- modules/common/document.go
- modules/common/fulltext.go
- modules/connector/connector.go
- modules/connector/datasource.go
- plugins/connectors/hugo_site/json.go
- plugins/connectors/hugo_site/plugin.go
> refactor: refactoring hugo_site connector to support mutlti datasource

- docs/content.en/docs/references/assistant.md
- docs/content.en/docs/references/connectors/google_drive.md
- plugins/connectors/google_drive/api.go
- plugins/connectors/google_drive/files.go
- plugins/connectors/google_drive/plugin.go
- plugins/connectors/yuque/collect.go
This pull request includes significant changes to the `plugins/connectors/google_drive` plugin, focusing on enhancing the handling of multiple data sources and improving file type recognition. The most important changes include updating function signatures to include `datasourceID`, modifying the `getIcon` function to support additional file types, and commenting out unused code.
Enhancements to data source handling:
* [`plugins/connectors/google_drive/api.go`](diffhunk://#diff-f3b2e174f74b46eae7e8a3d185d24e81e04846268b1561c78312b774123bd14bL84-R85): Updated function signatures to include `datasourceID` and modified the `getTenantKey` function to accommodate this new parameter. [[1]](diffhunk://#diff-f3b2e174f74b46eae7e8a3d185d24e81e04846268b1561c78312b774123bd14bL84-R85) …
> refactor: refactoring connectors

- modules/common/document.go
- plugins/connectors/yuque/collect.go
> chore: remove redundant last category if it matches the document title

- modules/common/datasource.go
- modules/connector/datasource.go
- modules/system/initialize.go
- plugins/connectors/google_drive/plugin.go
- plugins/connectors/hugo_site/plugin.go
- plugins/connectors/notion/plugin.go
- plugins/connectors/yuque/plugin.go
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/data-source/edit/[id].tsx
- web/src/pages/data-source/list/index.tsx
- web/src/pages/data-source/new/index.tsx
- web/src/types/api.d.ts
This pull request includes several changes to add synchronization control for data sources and improve the handling of ORM contexts. The most important changes include adding a `SyncEnabled` field to the `DataSource` struct, updating ORM operations to use a context with a refresh policy, and adding UI elements to control synchronization settings.
* [`modules/common/datasource.go`](diffhunk://#diff-90febfa38c364d2213123da5690c26e866036769c74600e76bebf47675efcf30R15-R16): Added a `SyncEnabled` field to the `DataSource` struct to indicate whether synchronization is allowed.
* `web/src/pages/data-source/edit/[id].tsx`, `web/src/pages/data-source/new/index.tsx`: Added a `Switch` component to the forms for creating and editing data sources to control the `sync_enabled` field. …
> feat: add field `SyncEnabled` to control datasource synchronization

- coco.yml
This pull request includes a small change to the `coco.yml` file. The change disables the proxy by setting the `enabled` field to `false`.
* [`coco.yml`](diffhunk://#diff-461bb31f066abaf4260e1409e70068530cccf332d5b44ce8174eb39cbc253e23L358-R358): Disabled the proxy by setting `enabled` to `false` under `http_client.default.proxy`.
> chore: update default proxy enabled to `false`

- docs/content.en/docs/getting-started/install.md
This pull request includes updates to the Docker image version used in the installation instructions for the Coco Server. The changes ensure that the documentation reflects the latest version of the Docker image.
Updates to Docker image version:
* [`docs/content.en/docs/getting-started/install.md`](diffhunk://#diff-9fa6f57fd4605d9676451a90930fe3c9fa0d0a47d6d3f972f2818d62b3fb6ac9L29-R30): Updated the Docker image version from `0.2.0-1992` to `0.2.1-1998` in multiple locations to ensure the documentation uses the latest image version. [[1]](diffhunk://#diff-9fa6f57fd4605d9676451a90930fe3c9fa0d0a47d6d3f972f2818d62b3fb6ac9L29-R30) [[2]](diffhunk://#diff-9fa6f57fd4605d9676451a90930fe3c9fa0d0a47d6d3f972f2818d62b3fb6ac9L43-R45) [[3]](diffhunk://#diff-9fa6f57fd4605d9676451a90930fe3c9fa0d0a47d6d3f9 …
> docs: upgrade to 0.2.1

- docs/content.en/docs/release-notes/_index.md
- modules/common/config.go
This pull request includes a small change to the `modules/common/config.go` file. The change adds the server version information to the `config.ServerInfo` object.
* [`modules/common/config.go`](diffhunk://#diff-468ab3f0b032c10ba17cbb82c0cdda2a7252fbc57c98c0ecc93486ee55f062eeR40): Added the server version to the `config.ServerInfo` object in the `AppConfig` function.
> fix: provider info version

- modules/system/initialize.go
This pull request includes an important change to the `modules/system/initialize.go` file to enhance the server setup process by automatically setting the server endpoint if it is not provided. 
Improvements to server setup:
* [`modules/system/initialize.go`](diffhunk://#diff-b78129ce01dbbb7ab2977a3ad2996658721102529f8da3a87ddee1e363274d1bR104-R110): Added logic to set the `ServerInfo.Endpoint` to a URL constructed from the request schema and host if it is not already specified. This ensures that the server endpoint is always correctly set, even if not explicitly provided.
> feat: initialize default server endpoint based on request

- docs/content.en/docs/release-notes/_index.md
- web/src/pages/connector/edit/[id].tsx
Set built-in connector icons as readonly
> feat: set built-in connector icons as readonly

- modules/search/search.go
return font icon key in query search API
> feat: add support for font icon in query search API

- docs/content.en/docs/release-notes/_index.md
- modules/connector/connector.go
- web/src/locales/langs/en-us/page.ts
- web/src/locales/langs/zh-cn/page.ts
- web/src/pages/data-source/new/google_drive.tsx
- web/src/pages/data-source/new/index.tsx
When creating a new Google Drive datasource, guide the user to configure the required settings if they are missing.
> improvement: check oauth config before creating new google drive datasource

- web/src/pages/mcp-server/modules/EditForm.tsx
handle empty MCP config when type is stdio
> fix: handle empty MCP config when type is stdio

- docs/content.en/docs/release-notes/_index.md
- modules/integration/wrapper.go
> fix: incorrect content-type header for wrapper

- docs/content.en/docs/release-notes/_index.md
- modules/system/init.go
> fix: add missing cors feature flags to settings api

- docs/content.en/docs/release-notes/_index.md
- web/src/components/datasource/type/urls.jsx
- web/src/pages/data-source/edit/[id].tsx
- web/src/pages/data-source/list/index.tsx
fix: handle empty URL values in HugoSite-type datasource
> fix: handle empty URL values in HugoSite-type datasource

- docs/content.en/docs/release-notes/_index.md
- web/src/pages/ai-assistant/modules/DatasourceConfig.tsx
- web/src/pages/ai-assistant/modules/MCPConfig.tsx
> fix: datasource & MCP selection problem

- docs/content.en/docs/release-notes/_index.md
- modules/common/assistant.go
- modules/system/init.go
Return number of assistants in provider info API
> feat: return number of assistants in provider info API

- docs/content.en/docs/getting-started/install.md
The old Tag does not exist in Docker. Update to use the latest one.
Update to use the latest one.
> docs: update to latest tag

- docs/content.en/docs/release-notes/_index.md
- modules/assistant/streaming-http.go
> chore: ignore empty chunk_message

- docs/content.en/docs/release-notes/_index.md
- modules/assistant/session.go
> fix: remove manually_renamed_title from assistant search

- web/src/pages/ai-assistant/list/index.tsx
- web/src/pages/mcp-server/list/index.tsx
- web/src/pages/model-provider/list/index.tsx
chore: make ai assistant, mcp server and llm provider names clickable and enter the edit mode by default
usability enhancement
> chore: make AI assistant, mcp server and LLM provider names clickable

- docs/content.en/docs/release-notes/_index.md
- web/src/pages/ai-assistant/list/index.tsx
- web/src/pages/model-provider/list/index.tsx
hide delete button for built-in assistants and providers
> improve: hide delete button for built-in assistants and providers

- docs/content.en/docs/getting-started/install.md
This commit adds shell script syntax highlight for the following section in `docs/content.en/docs/getting-started/install.md`:
> docs: enable syntax highlight for shell scripts

- docs/content.en/docs/release-notes/_index.md
- web/src/pages/model-provider/list/index.tsx
fix missing update of local model providers after enable operation
> fix: fix missing update of local model providers after enable operation

- config/setup/en-US/assistant.tpl
Bug Fix
English guide page data form is broken
> fix: English guide/setup page POST request data format error, http 400

- modules/assistant/background_job.go
- modules/assistant/session.go
assign created time when creating a new reply message to ensure correct message history sorting
> fix: assign created time when creating a new reply message

- docs/content.en/docs/release-notes/_index.md
- modules/connector/connector.go
- web/src/pages/connector/new/assets_icons.jsx
This pull request introduces a bug fix and a code improvement to enhance the reliability of icon management in the application. The most notable changes include replacing the logic for generating unique keys for icons with a more robust UUID-based approach and updating the release notes to reflect the fix.
* Updated the release notes to include a new fix: "generate unique icon key to prevent accidental deletion of all icons." (`docs/content.en/docs/release-notes/_index.md`)
* Replaced `new Date().getTime()` with `getUUID()` for generating unique keys in `AssetsIcons` to ensure uniqueness and prevent potential key collisions. (`web/src/pages/connector/new/assets_icons.jsx`) [[1]](diffhunk://#diff-f01486a4b69ef6f0a618da4ad09316c46e5384332fa38801d5fd755c79d8fc3aR7-R21) …
> fix: generate unique icon key to prevent accidental deletion of all icons
